name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04] # Specify the Ubuntu versions here
    steps:
      - name: 'Checkout from Git'
        uses: actions/checkout@v4
      - name: 'Display GCC version'
        run: g++ --version
      - name: 'Compile'
        run: |
            cmake -B build
            cd build
            make